worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    log_format stream_basic '$remote_addr [$time_local] '
                            '$protocol $status $bytes_sent $bytes_received '
                            '$session_time "$upstream_addr"';

    access_log /dev/stdout stream_basic;
    error_log /dev/stderr info;

    upstream gateways {
        least_conn;
        server gateway_1:7000 max_fails=1 fail_timeout=2s;
        server gateway_2:7000 max_fails=1 fail_timeout=2s;
    }

    server {
        listen 7000;
        proxy_connect_timeout 1s;
        proxy_timeout 30s;
        proxy_pass gateways;
    }
}
